package-lock.json
package.json
src/app/product/page.tsx
src/app/product/register/page.tsx
src/components/Filter.tsx
src/components/ProductCard.tsx
src/components/ProductCardGrid.tsx
src/components/ProductForm.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1tTRfyFsLxsw9w9qoqNZzUFU0agITiok%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=LV08ZLK)

Feature#77 카드 컴포넌트 추가

---

src/app/layout.tsx
src/app/page.tsx
src/app/pay/page.tsx
src/components/SSE.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19SgdBSSFFmnOUB5yHqy0E7WlNOwK7EY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=KPy6f-_)
sse 컴포넌트 추가

Feature#245 sse알림

---

src/components/MyPage/customerSelf/BoughtList/BoughtList.tsx
src/components/MyPage/customerSelf/SubscribeList/SubscribeList.tsx
src/components/MyPage/customerSelf/SubscribeList/SubscribeRow.tsx
src/components/MyPage/customerSelf/WishList/WishList.tsx
src/components/MyPage/sellerSelf/AuctionList/AuctionList.tsx
src/components/MyPage/sellerSelf/ReviewList/ReviewList.tsx
src/components/MyPage/sellerSelf/ReviewList/ReviewRow.tsx
src/components/OtherPage/SellerAuctionList.tsx
src/components/ProductCardGrid.tsx
src/model/deal.ts
src/model/page.ts
src/model/produce.ts
src/model/review.ts
src/model/wish.ts
src/service/api/review.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18A8IlPQJ3KFCGj2TIofjcQyO8fsJaI8%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=GvSkdf_)

Feature#264 pagination

---

src/components/MyPage/customerSelf/CustomerBannerSelf.tsx
src/components/MyPage/sellerSelf/SellerBannerSelf.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19lEjMiQsaLTpqgaO7DOybir6K6XO0j6g%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=XXmrqGS)

Feature#266 add link

---

src/app/layout.tsx
src/app/product/[slug]/page.tsx
src/components/DibButton.tsx
src/components/Header.tsx
src/components/NotificationButton.tsx
src/components/ProduceReview.tsx
src/components/SSE.tsx
src/model/alarm.ts
src/service/alarm.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19xk8XZRhicdprMfIad4a778XMGIwF2IBU%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=HrnHW7n)

Feature#250 찜하기

---

src/components/MyPage/customerSelf/CustomerBannerSelf.tsx
src/service/api/user.ts

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18xIRjf6lP6U2EkURtL9KuAM8t6xk5Zu7U%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=_qPcQ8s)
우선 탈퇴기능 소비자 배너에만 적용했고요
탈퇴기능은 시연해보지 않았습니다 혹시몰라서..

feat: 탈퇴 기능 추가

---

src/components/MyPage/customerSelf/PayModal.tsx
src/components/MyPage/customerSelf/SubscribeList/SubscribeList.tsx
src/components/MyPage/customerSelf/SubscribeList/SubsribeScroll.tsx
src/components/MyPage/sellerSelf/SellerBannerSelf.tsx
src/components/OtherPage/SellerAuctionList.tsx
src/components/OtherPage/SellerBannerOther.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19gwKIihDc7J7OydcKGdRwoItwd4GV7Eh4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=Ng0BvD8)

Feature#270 additional design

---

src/components/MyPage/sellerSelf/SellerTap.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1MhGBZfhzx8Np9aYyBXkQlANHEguCCPc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=AeQbQnK)

feat: 판매 통계 잠정 제거

---

src/components/ProductCardGrid.tsx

refactor : 안쓰는 코드 제거

---

src/app/consumer/modify/page.tsx

refactor : form placeholder 수정

---

src/components/ProduceAuction.tsx
src/service/alarm.ts

fix : 경매 가격 수정

---

src/components/MyPage/customerSelf/SubscribeList/SubscribeList.tsx
src/components/MyPage/customerSelf/WishList/WishRow.tsx
src/components/MyPage/sellerSelf/AuctionList/AuctionList.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1rs03LjgEN5Ln6GiIiheLNtNSOrUBA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=W8H1z0m)
구매자 구독 목록, 판매자 경매 목록 검색 탭 수정
수량을 무게로 잘못 표기한 오타 수정

Feature#278 fix mypage

---

src/components/MyPage/customerSelf/SubscribeList/SubscribeList.tsx
src/components/MyPage/sellerSelf/AuctionList/AuctionList.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1v7lWr6sHBy4H5Q727bwinxZd6MsrweFM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=zN_yo3B)

fix: 검색 탭 경매 타입 오타 수정

---

src/app/consumer/modify/page.tsx

feat : 프로필 수정 후 이동

---

src/app/pay/page.tsx

fix : pay redirect 경로 수정

---

src/service/alarm.ts

fix : link 경로 수정

---

src/components/AuctionCount.tsx
src/components/ProduceAuction.tsx

refactor : 경매 기본시간 1분으로 수정

---

src/app/seller/register/page.tsx

fix : 판매자 등록 기본값 수정

---

src/components/ProductCardGrid.tsx

fix : 농산물 검색 수정

---

src/app/seller/register/page.tsx

refactor : 판매자 전환후 경로 이동

---

src/components/ProductCardGrid.tsx

fix : refetch 옵션 수정

---

src/app/seller/register/page.tsx
src/components/ProductCardGrid.tsx

fix : 무한스크롤 검색 수정

---

src/components/ProductCardGrid.tsx

fix : 경매 버그 수정

---

src/components/ProductCardGrid.tsx

fix : 경매 리스트 수정

---

src/components/Search.tsx

fix : 검색 초기화

---

src/components/Search.tsx

fix : 검색 애니메이션 수정

---

src/components/OtherPage/SellerAuctionRow.tsx
src/components/OtherPage/SellerDealRow.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19b2wY7MTmYbrY0dcSLnBePnHJOTDyFA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=6GpNXIF)

fix: 타인 페이지 kg 글자 누락 해결

---

src/components/ProductCardGrid.tsx

fix : 경매 페이지 버그 수정

---

src/components/ProductCardGrid.tsx

fix : 검색 기능 수정

---

src/components/Header.tsx

design : 알림 버튼 위치 변경

---

src/app/consumer/modify/page.tsx
src/components/Uploader.tsx

fix : 회원 정보 수정 업데이트

---

src/components/LoginButton.tsx

fix : 로그아웃 기능 수정

---

src/components/MyPage/customerSelf/SubscribeList/SubsribeScroll.tsx
src/components/OtherPage/SellerBannerOther.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1LGFrku5qIadXF24OqE5PHEmiL5ntUzk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dlFJAy_)

feat: 구독자 취소를 하거나 tab이 변경되면 구독자 목록을 새롭게 불러온다.

---

src/components/MyPage/customerSelf/SubscribeList/SubsribeScroll.tsx

[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1LGFrku5qIadXF24OqE5PHEmiL5ntUzk%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=dlFJAy_)

fix: recoil import 수정
